### PR TITLE
Implemented queue service class with support for transactions

### PR DESCRIPTION
**Pull request by jeduardocosta**
- Create SimpleAmazonQueueTransactionalService to support transactional context, using complete method to delete message
- Add "VisibilityTimeout" configuration attribute
- Update nuget package version

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/AboutVT.html

### CODE REVIEW

**Comment by lfreneda** [comment]
Vou publicar no nuget assim que for pro windows, Ok?

**Comment by jeduardocosta** [comment]
Tranquilo.
Valeu.
:+1:

**Comment by lfreneda** [comment]
Valeu voce!

**Comment by lfreneda** [comment]
@jeduardocosta consegue gerar o package p mim? Eu faco upload la..

**Comment by jeduardocosta** [comment]
:+1:

**Pull request merged**
