### PR TITLE
Fixed missed call to Dispose method of class AmazonSqs

### PR DESCRIPTION
**Pull request by dmgandini**
There was an issue related to a missing Dispose call. That issue can lead to memory leak.

### CODE REVIEW

**Comment by lfreneda** [comment]
u r so hot <3

**Comment by dmgandini** [comment]
LOL
Would u mind to push to nuget?

**Comment by lfreneda** [comment]
https://www.nuget.org/packages/SimpleAmazonSQS/1.3.1

**Comment by dmgandini** [comment]
:+1: :heart:

**Pull request merged**
